project_id = "nmodpjhzxiqrwqqeetyd"

[functions.verify-edit-access]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.manage-project]
verify_jwt = false

[functions.cleanup-feedback]
verify_jwt = false
